### ISSUE TITLE
Compare- cannot

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_backup_file#12]
не вызвать diff, Ubuntu.

вызвал команду "...compare..".
диалог "имя бака". нажал ОК.
потом в консоли

```
[ 0.02"]Command.on_save_pre:355 sv_path=/home/user/test/bk/tst.004.htm
[ 0.05"]Command.on_save_pre:373 ok
[ 2.18"]Command.copy_bk_or_compare:245 sv_path=/home/user/test/bk/tst_02февр.17-14.htm
[ 2.21"]Command.copy_bk_or_compare:260 mask={FILE_STEM}_{DD}{MMM}{YY}-{hh}.{FILE_EXT}
[ 2.22"]Command.copy_bk_or_compare:282 mask=tst_\d\d\w\w\w\d\d-\d\d.htm
[ 3.83"]Command.copy_bk_or_compare:339 src, trg=('/home/user/test/tst.htm', '/home/user/test/bk/tst_02февр.17-14.htm')
```

и все

**Comment by kvichans** [comment]
А что должно происходить?
Если в шеле вызвать
  `diff -u "/home/user/test/tst.htm" "/home/user/test/bk/tst_02февр.17-14.htm"`
то что?

**Comment by Alexey-T** [comment]
открытие новой консоли. Диф- консол программа.

**Comment by kvichans** [comment]
А-а-а. Нужно в `Popen` указывать, что это шел-команда. ToDo

**Comment by kvichans** [comment]
Добавил настройку и изм. вызов Popen. Пробуйте

**Comment by Alexey-T** [comment]
В логе `[30.56"]Command.copy_bk_or_compare:342 src, trg=('/home/user/test/tst.htm', '/home/user/test/bk/tst_03февр.17-15и.htm')
`
и ничего

**Comment by kvichans** [comment]
Попробуйте вызывать в пи-консоли
`subprocess.Popen('diff -u "/home/user/test/tst.htm" "/home/user/test/bk/tst_03февр.17-15и.htm"', shell=True)`

**Comment by Alexey-T** [comment]
не видно окна diff.

**Comment by kvichans** [comment]
А HTML-файлы такие есть?
Попробуйте:
`subprocess.Popen(['diff', '-u', "/home/user/test/tst.htm", "/home/user/test/bk/tst_03февр.17-15и.htm"], shell=True)`

**Comment by Alexey-T** [comment]
файлы есть, заменить 'diff' - 'cudatext' и Ок.

**Comment by Alexey-T** [comment]
не проблема плагина. diff закрывается...
