### ISSUE TITLE
Lang

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_backup_file#13]
Сообщения, которые видит пользователь:
[messages.pot.txt](https://github.com/kvichans/cuda_backup_file/files/747617/messages.pot.txt)

**Comment by Alexey-T** [comment]
Commands \"Copy to\" and \"Diff with\" will use old state.
Нету 2х команд.Есть одна

**Comment by Alexey-T** [comment]
"Fail to create dir" --"Cannot create dir"

**Comment by Alexey-T** [comment]
"Create backup fail: invalid path"--"Cannot create backup copy...,,"

**Comment by Alexey-T** [comment]
"of parent directory"---?? Dir и так парент.

**Comment by Alexey-T** [comment]
"hour" "minute" "secobd"--надо множ. число

**Comment by kvichans** [comment]
>Commands "Copy to" and "Diff with" will use old state.
>Нету 2х команд.Есть одна

Так лучше?: 
```
Text modified!
The command will use old state.
Continue?
```

---
>"of parent directory"---?? Dir и так парент.

Да, невнятно получилось: `{FILE_DIR|p} - Path of parent directory of current file`.
`{FILE_DIR}` - это директория тек. файла.
`{FILE_DIR|p}` - это дир, в которую вложен `{FILE_DIR}`.
`{FILE_DIR|p:2}` - это еще на один уровень выше.
Есть идеи как это выразить?

**Comment by Alexey-T** [comment]
{FILE_DIR} - это директория тек. файла.
{FILE_DIR|p} - это дир, в которую вложен {FILE_DIR}.
{FILE_DIR|p:2} - это еще на один уровень выше.

- directory of current file
- directory level upper, than FILE_DIR
- directory 2 levels upper, than FILE_DIR

**Comment by Alexey-T** [comment]
Ваша правка ок.

**Comment by kvichans** [comment]
Поставил
```
{FILE_DIR}              Path of directory of current file
{FILE_DIR|name}         Name of directory of current file
{FILE_DIR|p}            Path of directory level upper, than {FILE_DIR}
{FILE_DIR|p|name}       Name of directory level upper, than {FILE_DIR}
```

**Comment by Alexey-T** [comment]
ok.
