### ISSUE TITLE
Add variant- er2

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_backup_file#14]
удалил конфиг.
Нажимаю add variant-
```
vTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_backup_file/cd_bk.py", line 458, in dlg_config
    ,diff=vds['diff']
KeyError: 'diff'
```

было так
![er-22](https://cloud.githubusercontent.com/assets/4154978/22551267/91ae5774-e96d-11e6-813e-61293c5140dc.png)

**Comment by kvichans** [comment]
Не повторил. Попробуйте на версии "0.8.2". Если повторяется, опишите подробнее.

**Comment by Alexey-T** [comment]
берете конфиг.
потом открыли длг.
нажимаете add-variant- ошибка.
[cuda_backup_file.zip](https://github.com/kvichans/cuda_backup_file/files/750054/cuda_backup_file.zip)

версия из GH.

**Comment by kvichans** [comment]
Какую из кнопок `Add var` нажимать?

**Comment by kvichans** [comment]
Не повторил (пробовал обе кнопки)

**Comment by Alexey-T** [comment]
может быть ош только в Лин.

**Comment by Alexey-T** [comment]
делаю дебаг-
er in line 462.
added, line 460:
```
 if adva and not vds['svon']:
                dma_path= get_bk_path(cf_path, vals['wher'], vals['mask'])
                print('>>', vds) ##########
```
выводит пустой дикт.
```
>> OrderedDict([('wher', '{FILE_DIR}/bk'), ('mask', '{FILE_STEM}_{DD}{MMM}{YY}-{hh}.{FILE_EXT}'), ('diff', 'diff -u "{COPY_PATH}" "{FILE_PATH}"'), ('dfmx', 0), ('svon', False), ('whon', '{FILE_DIR}/bk'), ('maon', '{FILE_STEM}.{COUNTER|w:3}.{FILE_EXT}'), ('dfsh', True)])
>> {'wher': '', 'maon': '', 'mask': '', 'svon': False, 'whon': ''}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/cuda/cuda/app/py/cuda_backup_file/cd_bk.py", line 463, in dlg_config
    ,diff=vds['diff']
KeyError: 'diff'

```

**Comment by kvichans** [comment]
Странно! 
В строке 417 стоит (есть у вас?)
`vds.setdefault('diff', self.def_diff)`
Потом значения внутри `vds` изменяются только в строках
`vds.update({k:v for (k,v) in vals.items() if k in ('wher', 'mask', 'diff', 'dfsh', 'dfmx', 'svon', 'whon', 'maon')})`
то есть перекидываются значения, полученные из диалога.
Включите печать vals
```
            if aid is None or aid=='-':    return#while True
            pass;              LOG and log('vals={}',(vals))
``` 
и повторите.
Какую кнопку `Add var` нажимаете? У них разные функции

**Comment by Alexey-T** [comment]
Нажимаю вариант Add-variant из комбобокса внизу

**Comment by kvichans** [comment]
Нда! Я же нажимал другое :)

**Comment by kvichans** [comment]
Повторил

**Comment by Alexey-T** [comment]
Нда..
