### ISSUE TITLE
Password-edit err

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_backup_file#15]
"edit" has new "props" at end. it makes password-kind.
Now i see in here

![pas-bak](https://cloud.githubusercontent.com/assets/4154978/22566373/0ab2dd66-e9a5-11e6-8855-ab89491d8e20.png)

**Comment by kvichans** [comment]
Это ошибка не моя, а ваша. Новые опции **не должны** ломать старые конфиги

**Comment by kvichans** [comment]
В вики написано по-старому
```
"props": control-specific properties:
    for edit, memo: bool_read_only+","+bool_font_monospaced+","+bool_show_border 
```

**Comment by Alexey-T** [comment]
Опция в конце "props", убрал ее. можно задать 3 числа. Плагин задает 4 числа. т.е. ош плагина, (когда была опция 4)

**Comment by kvichans** [comment]
>Плагин задает 4 числа

Не вижу это в плагине
