### ISSUE TITLE
wish- 2 cmd's

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_backup_file#16]
Create copy/ Compare- раузмно сделать 2 команды. разные акшены. (мне НЕ нужно делать compare)

**Comment by kvichans** [comment]
Уже думал в эту сторону. Будет в настройках отсечение "сравнений"

**Comment by kvichans** [comment]
Теперь можно выключить галку `and to compare` - будет всегда выполняться только backup

**Comment by Alexey-T** [comment]
Можно индент между кнопами 4 (6лучше) pix?

**Comment by kvichans** [comment]
ToDo
