### ISSUE TITLE
Дикий глюк в мак

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_backup_file#18]
показ диалога, видно More>>.
жму more.
Оконный менеджер спятил- движение мышы- мерцает окно- 10 раз в сек
еле нажал less<<
стало ок.

**Comment by Alexey-T** [comment]
галка auto-create- глюка не дает.

**Comment by kvichans** [comment]
Что за галка? Код как-то изменить?

**Comment by Alexey-T** [comment]
галка Auto-create backup on each sacing - меняет длг, глюка нет.
more>> глюк есть.

**Comment by kvichans** [comment]
нет идей

**Comment by Alexey-T** [comment]
идея- в Мак (только в Лаз) часто дергается контрол с act=1.
недоделка Лаз
