### ISSUE TITLE
Use encoding of text

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_backup_file#20]
Wish- учесть кодировку. бекап делать в тойже кодировке.
Wiki---> PROP_ENC: str: encoding name. Possible values are shown in menu of encodings.

ps. или плагин не читает текст?

**Comment by Alexey-T** [comment]
или плагин не читает текст?

**Comment by kvichans** [comment]
Этот плагин ни как не зависит от содержания файлов. Он выполняет только две команды с файлами
`  Popen( "diff_tool bk_file_path cur_file_path" )`
`  shutil.copyfile( cur_file_path,  bk_file_path )`
в которых используются ИМЕНА файлов.
