### ISSUE TITLE
incorrect .inf file

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_backup_file#22]
```
[ini1]
section=Events
id=on_save_pre
params=on_save_pre
```
Тут id некорректный- посмотрел пример плагинов- тут надо писать уник. слово для плагинов
Это будет ключ в .ini

Пример - id=BackupFile

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Может вы про Син?

**Comment by Alexey-T** [comment]
Да- про Син, не тот репо
