### ISSUE TITLE
Change deflt template

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_backup_file#5]
Linux app has template image_2017-01-25_12-31-51.png
pls use _ as lead- before date, middle- between date/time.

**Comment by kvichans** [comment]
Я вижу, что шаблон из вашего примера устроен так
`stem_YYYY-MM-DD_hh-mm-ss.ext`
в нем "_" разделяет `stem` `date` `time`.
Дам такой шаблон.

**Comment by Alexey-T** [comment]
stem- не то слово. лучше name, basename. https://studyenglishwords.com/words/stem

**Comment by kvichans** [comment]
> грамматика — основа

Как раз в этом смысле и применяется.
Это я не сам придумал, а взял из либы для работы с файлами MS Visual FoxPro.
