### ISSUE TITLE
Auto-bak dont work

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_backup_file#9]
открыл Куд
создал новый файл из пустого таб.
сохранил в ~/tst-bak/tst1.txt.

открыл длг опций, включил Авто.
делаю сейв того файла. Авто бака нету. папки bk нету.

**Comment by Alexey-T** [comment]
вышел-зашел в К. Бак работает.

**Comment by Alexey-T** [comment]
мешается дефолт с `\`. поправил в /.

**Comment by Alexey-T** [comment]
все еще нету папки bk и бекапа. При сейве msg_status-alt есть, путь ок. Бака нет

**Comment by Alexey-T** [comment]
Нету тут слеш перед home!

![bakpppp](https://cloud.githubusercontent.com/assets/4154978/22518087/c3e35414-e8c4-11e6-8799-eea51e355530.png)

**Comment by kvichans** [comment]
Какие значения в `settings\cuda_backup_file.json` у ключей `vrn_num`, `all_vrns`?

**Comment by Alexey-T** [comment]
```
  "all_vrns": [
        {
            "wher": "{FILE_DIR}/bk",
            "mask": "{FILE_STEM}_{DD}{MMM}{YY}-{hh}.{FILE_EXT}",
            "diff": "diff -u {BACKUP_PATH} {CURRENT_PATH}",
            "dfmx": 9,
            "svon": true,
            "whon": "{FILE_DIR}/bk",
            "maon": "{FILE_STEM}.{COUNTER|w:3}.{FILE_EXT}"
        }
    ],
    "vrn_num": 0,
```

**Comment by kvichans** [comment]
Из картинки не понятно в какой папке лежит файл `tst1.txt`.
Похоже проблема в том, что код удаляет `os.sep` с обоих концов, а в Лин начальный `/` содержательный.
ToDo
